config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root "guards#index"

  resources :guards
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/guard.rb
class Guard < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/guards_controller.rb
class GuardsController < ApplicationController
  before_action :set_guard, only: [:show, :edit, :update, :destroy]

  # GET /guards
  # GET /guards.json
  def index
    @guards = Guard.all
  end

  # GET /guards/1
  # GET /guards/1.json
  def show
  end

  # GET /guards/new
  def new
    @guard = Guard.new
  end

  # GET /guards/1/edit
  def edit
  end

  # POST /guards
  # POST /guards.json
  def create
    @guard = Guard.new(guard_params)

    respond_to do |format|
      if @guard.save
        format.html { redirect_to @guard, notice: 'Guard was successfully created.' }
        format.json { render :show, status: :created, location: @guard }
      else
        format.html { render :new }
        format.json { render json: @guard.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /guards/1
  # PATCH/PUT /guards/1.json
  def update
    respond_to do |format|
      if @guard.update(guard_params)
        format.html { redirect_to @guard, notice: 'Guard was successfully updated.' }
        format.json { render :show, status: :ok, location: @guard }
      else
        format.html { render :edit }
        format.json { render json: @guard.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /guards/1
  # DELETE /guards/1.json
  def destroy
    @guard.destroy
    respond_to do |format|
      format.html { redirect_to guards_url, notice: 'Guard was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_guard
    @guard = Guard.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def guard_params
    params.fetch(:guard, {}).permit(
        :first_name, :middle_name, :last_name, :birth,
        :registration_address, :actual_address, :employment,
        :fired, :validity_certificate, :validity_examination,
        :validity_medical_board, :avatar
    )
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/guards_helper.rb
module GuardsHelper
end

app/views/guards/_form.html.erb
<%= form_with(model: @guard, local: true) do |form| %>
  <% if @guard.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@guard.errors.count, "error") %> prohibited this guard from being saved:</h2>

      <ul>
      <% @guard.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label 'Фото' %>
    <%= form.file_field :avatar %>
  </div>
  <div>
    <%# image_tag(@guard.avatar) %>
  </div>

  <div class="actions">
    <%= form.label 'Фамилия' %>
    <%= form.text_field :last_name %>
  </div>

  <div class="actions">
    <%= form.label 'Имя' %>
    <%= form.text_field :first_name %>
  </div>

  <div class="actions">
    <%= form.label 'Отчество' %>
    <%= form.text_field :middle_name %>
  </div>

  <div class="actions">
    <%= form.label 'Дата рождения' %>
    <%= form.date_field :birth %>
  </div>

  <div class="actions">
    <%= form.label 'Адрес регистрации' %>
    <%= form.text_field :registration_address %>
  </div>

  <div class="actions">
    <%= form.label 'Фактический адрес' %>
    <%= form.text_field :actual_address %>
  </div>

  <div class="actions">
    <%= form.label 'Трудоустроен' %>
    <%= form.date_field :employment %>
  </div>

  <div class="actions">
    <%= form.label 'Уволен' %>
    <%= form.date_field :fired %>
  </div>

  <br><hr>

  <div class="actions">
    <%= form.label 'Удостоверение действительно до ' %>
    <%= form.date_field :validity_certificate %>
  </div>

  <div class="actions">
    <%= form.label 'Переодическая проверка действительна до ' %>
    <%= form.date_field :validity_examination %>
  </div>

  <div class="actions">
    <%= form.label 'Медкомиссия действительна до ' %>
    <%= form.date_field :validity_medical_board %>
  </div>

  <div class="actions">
    <%= form.submit 'сохранить' %>
  </div>
<% end %>

app/views/guards/edit.html.erb
<h1>Editing Guard</h1>

<%= render 'form', guard: @guard %>

<%= link_to 'Show', @guard %> |
<%= link_to 'Back', guards_path %>

app/views/guards/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Guards</h1>

<table>
  <thead>
    <tr>
      <td>№ п/п</td>
      <td>Фамилия</td>
      <td>Имя</td>
      <td>Отчество</td>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @guards.each_with_index do |guard, index| %>
      <tr>
        <td><%= index + 1 %></td>
        <td><%= guard.last_name %></td>
        <td><%= guard.first_name %></td>
        <td><%= guard.middle_name %></td>
        <td><%= link_to 'Show', guard %></td>
        <td><%= link_to 'Edit', edit_guard_path(guard) %></td>
        <td><%= link_to 'Destroy', guard, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Guard', new_guard_path %>

app/views/guards/new.html.erb
<h1>Добавить нового сотрудника</h1>

<%= render 'form', guard: @guard %>

<%= link_to 'Back', guards_path %>

app/views/guards/show.html.erb
<p id="notice"><%= notice %></p>

<%= @guard.last_name %><br>
<%= @guard.first_name %><br>
<%= @guard.middle_name %><br><br>
<%= "родился: " + "#{@guard.birth}" %><br>
<%= "адрес регистрации: " + "#{@guard.registration_address}" %><br>
<%= "фактичкский адрес: " + "#{@guard.actual_address}" %><br>
<%= "трудоустроен: " + "#{@guard.employment}" %><br>
<%= "уволен: " + "#{@guard.fired}" %><br><hr>
<%= "Актуальность документов" %><br><br>
<%= "удостоверение действительно до: " + "#{@guard.validity_certificate}" %><br>
<%= "периодическая проверка действительна до: " + "#{@guard.validity_examination}" %><br>
<%= "медкомиссия действительна до: " + "#{@guard.validity_medical_board}" %><br><hr>

<%= link_to 'изменить', edit_guard_path(@guard) %> |
<%= link_to 'назад', guards_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>SecurityGuards</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>